site_name: The Universal PL Project
site_author: Joshua Otten, Kevin Moran, Antonis Anastasopoulos
copyright: '©2023'

nav:
  - Home: index.md


theme:
  name: 'material'
  logo: 'images/sage-logo.png'
  favicon: 'images/sage-logo.png'
  font: false

  icon:
    admonition:
      success: fontawesome/solid/square-rss
      tip: fontawesome/solid/file-lines
      example: fontawesome/solid/screwdriver-wrench
      note: fontawesome/solid/book
      abstract: fontawesome/solid/database


  features:
    - navigation.tabs

  palette:

 # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: gmu 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      toc_depth: 3
  - attr_list
  - meta
  - attr_list
  - md_in_html

plugins:
    - search
    - encryptcontent:
        title_prefix: '[Protected]'
        summary: 'This Content is Password Protected'
        placeholder: 'Click here to type the Password, then press Enter'
        decryption_failure_message: 'Invalid Password'
        encryption_info_message: 'This course content is password protected. Please enter the password.'
    - meta:
       meta_file: '**/.meta.yml'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sageselab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sageselab